---
version: '3'

volumes:
  consul_data:
    name: lk_consul_data
    # external: true
  loki_data:
    name: loki_data
    # external: true
  nginx_data: {}

services:

  # # Loki gateway
  # loki-nginx:
  #   image: nginx
  #   ports:
  #     - 3101:3101
  #   volumes:
  #     - ./configs/loki-nginx/default.conf:/etc/nginx/conf.d/default.conf

  consul:
    image: docker-hub-repos.myket.ir/consul:1.15
    volumes:
      - consul_data:/consul/data
      # - ./configs/consul/config.json:/consul/config/config.json:ro
    environment:
      CONSUL_BIND_INTERFACE: eth0
    expose:
      - 8500
    restart: unless-stopped


  redis:
    image: docker-hub-repos.myket.ir/redis:6-alpine
    expose:
      - 6379
    restart: unless-stopped


  loki:
    image: docker-hub-repos.myket.ir/grafana/loki:2.5.0
    volumes:
      - ./configs/loki:/etc/loki
      - ./configs/loki/rules:/tmp/loki/rules/fake:ro
      - loki_data:/loki
    command: -config.expand-env -config.file=/etc/loki/loki.yml
    env_file:
      - ./configs/.loki.env
    depends_on:
      - consul
      - redis
    ports:
      - 3100:3100
    restart: unless-stopped


#  promtail:
#    image: grafana/promtail:2.2.1
#    container_name: promtail
#    volumes:
#      - ./configs/promtail:/etc/promtail
#      - /var/log:/var/log
#    command: -config.file=/etc/promtail/config.yml
#    networks:
#      - loki
#    restart: always