---
server:
  http_listen_port: 9080

positions:
  filename: /var/tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: promtail_nginxlogs
      instance: nginx1
      log_type: error
      __path__: /var/log/nginx/error1.log
