groups:
  - name: NginxErrorRate
    interval: 1m
    rules:
      - record: nginx:fluentbit_raw_errors:rate5m
        expr: sum(rate({job="fluentbit_nginxlogs", log_type="error"}[5m])) by (instance)
      - record: nginx:promtail_raw_errors:rate5m
        expr: sum(rate({job="promtail_nginxlogs", log_type="error"}[5m])) by (instance)
