---
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  # grpc_listen_address: 0.0.0.0
  # grpc_listen_port: 9095
  log_level: warn
  # http_path_prefix: "/loki/"

ingester:
  lifecycler:
    ring:
      kvstore:
        store: consul
        consul:
          host: ${LOKI_CONSUL_HOST:-consul:8500}
      replication_factor: 1
  max_transfer_retries: 0
  chunk_idle_period: 5m
  chunk_retain_period: 1m
  chunk_encoding: snappy
  wal:
    enabled: true
    dir: /loki/wal
    flush_on_shutdown: true

schema_config:
  configs:
    - from: 2020-08-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    shared_store: filesystem
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache

  filesystem:
    directory: /loki/chunks

  index_queries_cache_config:
    redis:
      endpoint: ${LOKI_REDIS_HOST:-redis:6379}
      # expiration: 24h

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  # reject_old_samples_max_age: 30m
  # ingestion_rate_mb: 10
  # ingestion_burst_size_mb: 20
  # max_cache_freshness_per_query: 10m
  retention_period: 30d
  split_queries_by_interval: 1h
  max_query_parallelism: 32

chunk_store_config:
  chunk_cache_config:
    redis:
      endpoint: ${LOKI_REDIS_HOST:-redis:6379}
      expiration: 8h
  write_dedupe_cache_config:
    redis:
      endpoint: ${LOKI_REDIS_HOST:-redis:6379}
      expiration: 8h

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  # parallelize queries in 15min intervals
  parallelise_shardable_queries: true
  # cache_results: true

  results_cache:
    cache:
      # # We're going to use the in-process "FIFO" cache
      # enable_fifocache: true
      # fifocache:
      #   size: 1024
      #   validity: 24h
      redis:
        endpoint: ${LOKI_REDIS_HOST:-redis:6379}
        expiration: 24h

query_scheduler:
  max_outstanding_requests_per_tenant: 4096

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  # downstream_url: ${FRONTEND_DOWNSTREAM_URL}
  max_outstanding_per_tenant: 4096

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  retention_enabled: true

ruler:
  wal:
    dir: /tmp/rule-wal
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /loki/rules-temp
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  # enable_alertmanager_v2: true
  # alertmanager_url: http://alertmanager:9093
  remote_write:
    enabled: true
    client:
      url: http://prometheus:9090/api/v1/write
      basic_auth:
        username: loki
        password: admin123
          #password: $2b$12$HYLVMTMy/PNGli7YIweheOfvktFi6.UEPql5F4FyHZ4kUNM5JpHlK
